### ISSUE TITLE
Sidebar bullet for active link displaying multiple times

### ISSUE THREAD

**Issue by Ragura** [mrcrmn/docc#5]
Hi, love what you've done with this simple template for a doc site. I'm looking into converting my Vuepress site to Gridsome and this looked like a perfect fit. Only thing I'm missing is support for Vue components in markdown, maybe something for the future?

Anyway, the issue I've discovered is that the bullet next to the active link on the sidebar is displayed multiple times when navigating from one link to another. I haven't found the logic to it, but I can click from one link to another to make two or even three bullets appear simultaneously.

Using latest Safari on Mac.

<img width="184" alt="Screenshot 2020-03-07 at 15 15 26" src="https://user-images.githubusercontent.com/16363147/76145138-1658ef00-6087-11ea-8938-8353e0a8f7e8.png">

**Comment by mrcrmn** [comment]
Thank you :)

I was able to reproduce the issue and fix it in fdd490d3e2484a6598924401c62928e190b12c47
Thank you for bringing it to my attention!

I have explored being able to use Vue Components in markdown using [@gridsome/vue-remark](https://gridsome.org/plugins/@gridsome/vue-remark) in the beginning but couldn't get it to work the way I wanted to.

It is definitely something I want to add in the future.
